# Numpy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.20.3


In [3]:
my_list = [1,2,3,4,5]
np1 = np.array(my_list)

print(np1)

[1 2 3 4 5]


In [4]:
type(np1)

numpy.ndarray

In [5]:
my_list1 = [[1,2,3],[4,5,6],[7,8,9]]
np2 = np.array(my_list1)

print(np2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Numpy built-in Functions

### arange - returns evenly spaced values in the given interval

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1.5,10.5)

array([1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [8]:
np.arange(5,100,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

### Zeros and ones

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace - same as arange (returns evenly spaced values)

In [14]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [16]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### Eye - returns identity matrix

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Generating random numbers

Creates an array of given shape and then populates it with random samples of uniform distribution over [0,1]



In [19]:
np.random.rand(3)

array([0.88852394, 0.59443213, 0.99615827])

In [21]:
np.random.rand(3,3)

array([[0.97163829, 0.90859395, 0.92598737],
       [0.47767492, 0.79498895, 0.34608415],
       [0.65148651, 0.14963384, 0.32459612]])

randn

returns a sample with standard normal distribution

In [25]:
np.random.randn(2)

array([ 0.77916641, -0.02032824])

In [24]:
np.random.randn(2,3)

array([[-0.98417399,  0.44947984,  0.91030547],
       [-1.87045196,  0.72086744, -0.10258737]])

randint

generate random integers

In [34]:
np.random.randint(2)


1

In [38]:
np.random.randint(2,30,20)

array([11, 26, 24, 24, 15, 11, 22, 29, 11, 16,  7, 25, 24, 19,  9, 16, 18,
       16,  4, 20])

In [40]:
arr1 = np.arange(1,20)

In [41]:
arr2 = np.random.randint(0,50,10)

In [42]:
arr1.shape

(19,)

In [43]:
arr2.shape

(10,)

In [45]:
arr1.max()

19

In [46]:
arr2.min()

0

In [47]:
print(arr1)

arr1.argmax()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


18

In [48]:
arr2.argmin()

5

argsort - performs sort and returns indices of the correct values as per the sort

argmax() - returns index of the max element in the array

In [51]:
arr2.argsort()

array([5, 6, 2, 3, 0, 7, 1, 8, 9, 4])

In [52]:
arr1.shape

(19,)

In [58]:
arr1 = np.arange(0,25)
print(arr1.shape)

arr1.reshape(5,5)

(25,)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
arr1 = np.arange(1,101)

arr1.reshape(10,10)

print(arr1.shape)

(100,)


In [59]:
arr1.dtype

dtype('int64')

In [60]:
arr1.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300])

In [69]:
arr3 = np.arange(1,5)
np.prod(arr3)

24

In [78]:
arr1 = [[1,2,3,4],[5,6,7,8]]

np.ravel(arr1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [82]:
np.arange(0.01,1,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

## Indexing and slicing

In [83]:
arr1 = np.arange(1,10)

In [84]:
arr1[8]

9

In [85]:
arr1[0:3]

array([1, 2, 3])

In [86]:
arr1[:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr1[0:3] = 100
arr1

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [90]:
arr = np.arange(0,25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
arr[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [93]:
arr[1:,3:]

array([[ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

In [97]:
arr[1:3,0:2]

array([[ 5,  6],
       [10, 11]])

In [98]:
arr[3][2]

17

In [99]:
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])